repos:
-   repo: https://github.com/JulienPalard/powrap
    rev: master
    hooks:
    -   id: powrap
-   repo: local
    hooks:
    -   id: merge-dicts
    -   name: merge-dicts
    -   entry: bash -c 'awk 1 dict dictionaries/*.txt > dict.txt'
   # from the example
   # -   entry: bash -c 'lines=$(pylint api/ | wc -l) && (( lines > 10)) && exit 1'
   # - language: system
# This one requires package ``hunspell-es_es`` in Archlinux
-   repo: https://github.com/humitos/pospell
    rev: pre-commit
    hooks:
    -   id: pospell
        args: ['--personal-dict', 'dict', '--modified', '--language', 'es_ES', '--language', 'es_AR']
