repos:
-   repo: https://github.com/humitos/powrap
    rev: pre-commit
    hooks:
    -   id: powrap

-   repo: https://github.com/humitos/pospell
    rev: pre-commit
    hooks:
    -   id: pospell
        args: ['--personal-dict', 'dict', '--modified']
